### ISSUE TITLE
"...?foo" syntax is ugly

### ISSUE THREAD

**Issue by Hixie** [munificent/ui-as-code#16]
I really like the bulk of the spread operator proposal (https://github.com/munificent/ui-as-code/blob/master/in-progress/spread-collections.md).

I am slightly concerned about the proposal at the end for a null-aware spread. I think it's important to support something like that, but the syntax `...?foo` seems more line-noisy than idiomatic Dart.

Not sure what else to suggest, though. I agree that `...?` is a logical way to express this.

**Comment by munificent** [comment]
Yeah, I agree it's pretty punctuation-heavy, but it's probably the natural-est solution.

**Comment by Hixie** [comment]
Part of my concern is that I think this will be pretty common (unlike some of the other punctuationy things in Dart), and I fear Dart turning into Perl. :-)

The other part of my concern is that usually the question mark is after the thing that you're null-checking, not before:

`foo ?? bar` is about `foo` being null
`foo ??= bar` is about `foo` being null
`foo?.bar` is about `foo` being null
`...?bar` is about `bar` being null

Maybe if it was more like `...bar?` it would be clearer? But it would be harder to parse.

Maybe the `...` should be on the rhs in general?

```dart
var args = [
  testArgs...,
  '--packages=${PackageMap.globalPackagesPath}',
  '-rexpanded',
  filePaths...
];

Widget build(BuildContext context) {
  return new CupertinoPageScaffold(
    child: new ListView(
      children: <Widget>[
        new Tab2Header(),
        buildTab2Conversation()...,
      ],
    ),
  );
}

var params = {
  "userId": 123,
  "timeout": 300,
  uri.queryParameters...
};

[1, "234".runes..., 5]

var first = {"key": "value"};
var second = {"a": "b", first..., "c": "d"};

var command = [
  engineDartPath,
  '--target=flutter',
  extraFrontEndOptions...?,
  mainPath
];
```

I kinda like that better in general, actually. It reads more like English. Would it be sufficiently unambiguous to parse?

**Comment by Hixie** [comment]
those seem equally confusing to me... `...`, whether as prefix or suffix, looks like it binds more tightly than `+`. (That's a problem we run into with `..`, where it looks like it binds more tightly than it does, which makes the code a bit confusing to read sometimes... to the point where sometimes I encourage people to add more parens than strictly necessary.)

If we make `...` bind tightly, it would end up being one of these:

```dart
var command = [
  engineDartPath,
  ...(stuff + moreStuff),
  another,
  (stuff + moreStuff)...,
  more
];
```

Both work ok here, but I think I prefer the latter. What about something more elaborate:

```dart
  var arguments = <String, Object>{
    'foo': bar,
    ...?tabStops?.map<String, Object>(
      (String int, Direction direction) => new MapEntry('--tab$int', direction.toString()),
    ),
    'baz': quux,
  };

  var arguments = <String, Object>{
    'foo': bar,
    tabStops?.map<String, Object>(
      (String int, Direction direction) => new MapEntry('--tab$int', direction.toString())
    )...?,
    'baz': quux,
  };
```

I think the suffix form has a (very) slight edge, mostly because it's not actually necessary to understand the code (obviously if it's valid code, and you have a random expression in the middle of the literal, it's going to be adding that value to the map -- the `...` is only really required to disambiguate between adding the list itself or expanding the list, in the case of a list literal where the list itself would be a valid value). Since it's not strictly necessary for readability, the prefix form is IMHO slightly hurt by the in-your-face-ness of its leading `?` coming before an alphabetic character and it being before the thing you're null-checking instead. (Especially egregious in the example above where there's a question mark before and after the first identifier.)

**Comment by munificent** [comment]
Closing since this syntax is locked down now.
