### ISSUE TITLE
Non-trailing optional parameters

### ISSUE THREAD

**Issue by mdebbar** [munificent/ui-as-code#20]
I was going through the parameter-freedom proposal and wanted to comment on something but I didn't know how, so I'm leaving my comment as a github issue:

The reason all languages require optional parameters to appear in the end is because of ambiguities in cases like this:
```dart
void foo([int x = 0, int y = 0], int z) {
  // ...
}

foo(10, 20);
```
Obviously, the 20 goes to `z` in the above example. But what about the 10? If the 10 goes to `x`, then it feels weird that I'm passing two adjacent arguments 10 and 20, but they are going to the 1st and 3rd parameter.

Just my 2 cents :) And great work by the way, I love this project!

Also, there's been some relevant discussions here: https://github.com/dart-lang/language/issues/58 about rest parameters.

**Comment by munificent** [comment]
> I was going through the parameter-freedom proposal and wanted to comment on something but I didn't know how, so I'm leaving my comment as a github issue

Yup, that's fine. :)

You can also file issues on the [language repo](https://github.com/dart-lang/language) as this work migrates over there. (I started in this repo before the language repo had been set up, but now that that's up and running, I'm gradually moving this over there.)

> The reason all languages require optional parameters to appear in the end is because of ambiguities in cases like this

Ruby actually doesn't require optional parameters to be trailing.

> But what about the 10? If the 10 goes to x, then it feels weird that I'm passing two adjacent arguments 10 and 20, but they are going to the 1st and 3rd parameter.

The parameter freedom proposal lays out what happens here. It does the same thing that Ruby does, which is that 10 goes to x. It is a little weird that it "skips" over a parameter, but the signature of that function is kind of weird too. If you design weird APIs, it's gonna feel weird to use them. :)

**Comment by mdebbar** [comment]
> Ruby actually doesn't require optional parameters to be trailing.

I didn't know Ruby allowed that so I just looked at it. It's confusing at best and requires extra-concentration and mental gymnastics to figure out which value is going to which parameter 🤔 I've yet to see a strong, practical use case for this pattern.

> The parameter freedom proposal lays out what happens here.

I know 😊 I'm just using it as an example to explain the ambiguity and confusion.

To be honest, I'm not a big fan of APIs that behave differently based on the number of arguments. Or, god forbid, the jQuery-like APIs that have a gazillion combinations of args.

**Comment by munificent** [comment]
> To be honest, I'm not a big fan of APIs that behave differently based on the number of arguments.

In general, any language feature can be overused to the point of regret and I don't think overloading is any different in that respect. But it is really handy to be able to omit certain parameters in some cases. Dart's current rules for handling that cover a lot of the useful cases but not quite all of them.
