### ISSUE TITLE
Rename Goals.md to Principles.md

### ISSUE THREAD

**Issue by yjbanov** [munificent/ui-as-code#3]
The `Goals.md` document reads more like a set of guiding principles than a _goals_ document. I imagined the goals would be along the lines of making UI code more readable, writable, bug-free, performant, etc. However, `Goals.md` seems to focus more on what _not_ to do; don't be too Flutter/UI-centric; don't conflict with the Dart language.

**Comment by munificent** [comment]
Yeah, maybe the title is confusing. "Guiding Principles" would work for me modulo my mild aversion to having a space in the filename. :)

What about "Principles" or "Constraints"?

**Comment by yjbanov** [comment]
:+1:
